import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useCallback } from 'react';

// Types for hospital system
export interface HospitalPatientDB {
  id: string;
  health_id: string;
  user_id: string | null;
  name: string;
  phone: string;
  aadhaar: string;
  email: string;
  date_of_birth: string | null;
  gender: string;
  blood_group: string;
  allergies: string;
  chronic_diseases: string;
  photo_url: string;
  family_head_id: string | null;
  is_family_head: boolean;
  language_preference: string;
  total_visits: number;
  last_visit_date: string | null;
  last_visit_summary: string;
  loyalty_points: number;
  created_at: string;
}

export interface HospitalTokenDB {
  id: string;
  token_number: number;
  patient_id: string;
  department_id: string | null;
  doctor_id: string | null;
  token_date: string;
  qr_code: string;
  entry_type: string;
  is_emergency: boolean;
  severity: string;
  symptoms: string;
  ai_suggested_department: string;
  status: string;
  is_follow_up: boolean;
  follow_up_from: string | null;
  estimated_wait_minutes: number;
  queue_position: number;
  created_at: string;
}

export interface HospitalDepartmentDB {
  id: string;
  name: string;
  floor: string;
  description: string;
  icon: string;
  is_active: boolean;
}

export interface HospitalDoctorDB {
  id: string;
  user_id: string;
  department_id: string | null;
  name: string;
  qualification: string;
  speciality: string;
  experience_years: number;
  availability_status: string;
  is_verified: boolean;
  rating_avg: number;
  rating_count: number;
  room_number: string;
}

export interface HospitalVisitDB {
  id: string;
  token_id: string;
  patient_id: string;
  doctor_id: string | null;
  symptoms: string;
  diagnosis: string;
  notes: string;
  prescription: any[];
  next_steps: any[];
  follow_up_days: number | null;
  follow_up_date: string | null;
  patient_rating: number | null;
  patient_feedback: string;
  drug_warnings: any[];
  ai_suggestions: any[];
  visit_stage: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface HospitalOrderDB {
  id: string;
  visit_id: string;
  token_id: string;
  patient_id: string;
  referring_doctor_id: string | null;
  order_type: string;
  centre_name: string;
  floor_location: string;
  order_details: string;
  medicines: any[];
  scan_type: string;
  lab_tests: any[];
  injection_details: string;
  result_data: any;
  result_notes: string;
  result_uploaded_at: string | null;
  status: string;
  seen_at: string | null;
  queue_position: number;
  created_at: string;
}

export function useHospitalDB() {
  const { user } = useAuth();

  // Departments
  const getDepartments = useCallback(async () => {
    const { data, error } = await supabase
      .from('hospital_departments')
      .select('*')
      .eq('is_active', true)
      .order('name');
    if (error) throw error;
    return data as HospitalDepartmentDB[];
  }, []);

  // Doctors
  const getDoctors = useCallback(async () => {
    const { data, error } = await supabase
      .from('hospital_doctors')
      .select('*')
      .order('name');
    if (error) throw error;
    return data as HospitalDoctorDB[];
  }, []);

  // Patients
  const searchPatient = useCallback(async (query: string) => {
    const { data, error } = await supabase
      .from('hospital_patients')
      .select('*')
      .or(`phone.ilike.%${query}%,aadhaar.ilike.%${query}%,name.ilike.%${query}%,health_id.ilike.%${query}%`)
      .limit(10);
    if (error) throw error;
    return data as HospitalPatientDB[];
  }, []);

  const registerPatient = useCallback(async (patient: {
    name: string;
    phone: string;
    aadhaar?: string;
    email?: string;
    date_of_birth?: string;
    gender: string;
    blood_group?: string;
    allergies?: string;
    chronic_diseases?: string;
    language_preference?: string;
    family_head_id?: string;
  }) => {
    const { data, error } = await supabase
      .from('hospital_patients')
      .insert({
        ...patient,
        user_id: user?.id || null,
        health_id: '', // will be auto-generated by trigger
      })
      .select()
      .single();
    if (error) throw error;
    return data as HospitalPatientDB;
  }, [user]);

  // Tokens
  const createToken = useCallback(async (token: {
    patient_id: string;
    department_id?: string;
    doctor_id?: string;
    entry_type: 'online' | 'offline';
    is_emergency?: boolean;
    severity?: string;
    symptoms?: string;
    ai_suggested_department?: string;
    is_follow_up?: boolean;
    follow_up_from?: string;
  }) => {
    const { data, error } = await supabase
      .from('hospital_tokens')
      .insert({
        ...token,
        token_number: 0, // auto-generated by trigger
      })
      .select()
      .single();
    if (error) throw error;
    return data as HospitalTokenDB;
  }, []);

  const getTodayTokens = useCallback(async (departmentId?: string) => {
    let query = supabase
      .from('hospital_tokens')
      .select('*')
      .eq('token_date', new Date().toISOString().split('T')[0])
      .order('token_number');
    if (departmentId) query = query.eq('department_id', departmentId);
    const { data, error } = await query;
    if (error) throw error;
    return data as HospitalTokenDB[];
  }, []);

  const updateTokenStatus = useCallback(async (tokenId: string, status: string) => {
    const { error } = await supabase
      .from('hospital_tokens')
      .update({ status })
      .eq('id', tokenId);
    if (error) throw error;
  }, []);

  // Visits
  const createVisit = useCallback(async (visit: {
    token_id: string;
    patient_id: string;
    doctor_id?: string;
    symptoms?: string;
  }) => {
    const { data, error } = await supabase
      .from('hospital_visits')
      .insert({
        ...visit,
        started_at: new Date().toISOString(),
      })
      .select()
      .single();
    if (error) throw error;
    return data as HospitalVisitDB;
  }, []);

  const updateVisit = useCallback(async (visitId: string, updates: Partial<HospitalVisitDB>) => {
    const { error } = await supabase
      .from('hospital_visits')
      .update(updates)
      .eq('id', visitId);
    if (error) throw error;
  }, []);

  const getPatientVisits = useCallback(async (patientId: string) => {
    const { data, error } = await supabase
      .from('hospital_visits')
      .select('*')
      .eq('patient_id', patientId)
      .order('created_at', { ascending: false });
    if (error) throw error;
    return data as HospitalVisitDB[];
  }, []);

  // Orders
  const createOrder = useCallback(async (order: {
    visit_id: string;
    token_id: string;
    patient_id: string;
    referring_doctor_id?: string;
    order_type: 'scan' | 'lab' | 'injection' | 'pharmacy';
    order_details?: string;
    medicines?: any[];
    scan_type?: string;
    lab_tests?: any[];
    injection_details?: string;
  }) => {
    const { data, error } = await supabase
      .from('hospital_orders')
      .insert(order)
      .select()
      .single();
    if (error) throw error;
    return data as HospitalOrderDB;
  }, []);

  const getOrdersByType = useCallback(async (orderType: string) => {
    const { data, error } = await supabase
      .from('hospital_orders')
      .select('*')
      .eq('order_type', orderType)
      .in('status', ['pending', 'seen', 'in_progress'])
      .order('created_at');
    if (error) throw error;
    return data as HospitalOrderDB[];
  }, []);

  const updateOrderStatus = useCallback(async (orderId: string, status: string) => {
    const updates: any = { status };
    if (status === 'seen') updates.seen_at = new Date().toISOString();
    if (status === 'in_progress') updates.started_at = new Date().toISOString();
    if (status === 'completed') updates.completed_at = new Date().toISOString();
    const { error } = await supabase
      .from('hospital_orders')
      .update(updates)
      .eq('id', orderId);
    if (error) throw error;
  }, []);

  // Notifications log
  const addNotificationLog = useCallback(async (notif: {
    token_id?: string;
    patient_id?: string;
    stage: string;
    message: string;
    channel?: string;
  }) => {
    const { error } = await supabase
      .from('hospital_notifications_log')
      .insert(notif);
    if (error) console.error('Notification log error:', error);
  }, []);

  return {
    getDepartments,
    getDoctors,
    searchPatient,
    registerPatient,
    createToken,
    getTodayTokens,
    updateTokenStatus,
    createVisit,
    updateVisit,
    getPatientVisits,
    createOrder,
    getOrdersByType,
    updateOrderStatus,
    addNotificationLog,
  };
}
